# Insert your Discord webhook URL below
URL: "PUT YOUR WEBHOOK URL HERE"

# If true, this plugin will ignore commands run by people that are not opped
Only log OPs: true

# A list of commands to ignore
Command Blacklist: "/tell /r /home"